name: Run AlimAI Telegram Bot (for testing/verification) # Workflow এর নাম

on:
  push:
    branches:
      - main # যখন main ব্রাঞ্চে কোড পুশ করা হবে, তখন এটি ট্রিগার হবে।
  workflow_dispatch: # হাতে চালানো (Manually trigger) করার অনুমতি দেয়।

jobs:
  run_bot:
    runs-on: ubuntu-latest # এই Workflow Ubuntu অপারেটিং সিস্টেমে চলবে।

    steps:
    - name: Checkout code # GitHub রিপোজিটরি থেকে কোড চেকআউট (ডাউনলোড) করে।
      uses: actions/checkout@v2

    - name: Set up Python # পাইথন এনভায়রনমেন্ট সেটআপ করে।
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # আপনার প্রোজেক্টের জন্য ব্যবহৃত পাইথন ভার্সন। প্রয়োজন অনুযায়ী পরিবর্তন করুন।

    - name: Install dependencies # requirements.txt ফাইলে উল্লেখিত সকল পাইথন লাইব্রেরি ইনস্টল করে।
      run: pip install -r requirements.txt

    - name: Run AlimAI Bot # আপনার বটকে চালানোর চেষ্টা করে।
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }} # GitHub Secrets থেকে Telegram Bot Token নেয়।
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} # GitHub Secrets থেকে Gemini API Key নেয়।
      run: |
        echo "Starting AlimAI Bot..."
        python bot.py
        echo "AlimAI Bot has finished its run." # GitHub Actions এর এই ধাপটি শেষ হবে যখন bot.py শেষ হবে।
